services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]

    # Handle API Manager as a factored Service
    Vrpayment\ContaoIsotopeBundle\Api\ApiManagerFactory: ~

    Vrpayment\ContaoIsotopeBundle\Api\ApiManager:
        class: Vrpayment\ContaoIsotopeBundle\Api\ApiManager
        factory: ['@Vrpayment\ContaoIsotopeBundle\Api\ApiManagerFactory', createApiManager]
        public: true
        autowire: true
        arguments:
            - "@doctrine.dbal.default_connection"
            - "@monolog.logger"
        tags:
            - { name: monolog.logger, channel: app }

